export const HOME = "/";
export const SERVICES = "/services";
export const BLOGS = "/blogs";
export const CONTACT = "/contact";
export const SIGNIN = "/signin";
export const SIGNUP = "/signup";
export const BLOGPAGE = "/blogpage";
export const DASHBOARD = "/dashboard";
export const PROFILE = "/dashboard?tab=profile";
export const SIGNOUT = "/dashboard?tab=signout";
// export const SIGNOUT = "/signout";
