export const DashboardCSS = {
  main: {
    display: "flex",
    minHeight: "80vh",
  },
  sideMain: {
    // position: 'relative',
    // backgroundColor: "#304fa177",
    minWidth: "300px",
    height: "80vh",
    p: 1,
    // overflowY: "scroll",
    // overflowX: "hidden",
  },
  tabTitle: {
    m: 1,
    // py: 0,
    borderRadius: "10px",
    transition: "all 0.3s ease-in-out",
    textTransform: "capitalize",
    textAlign: "left",
    fontFamily: "Krona One",
    fontSize: "1rem",
    display: "flex",
    // height: "20px !important",
    justifyContent: "start",
    alignItems: "center",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#304fa1",
      color: "#fff",
    },
  },
  tabActive: {
    backgroundColor: "#304fa1",
    color: "#fff !important",
  },
  tabIcon: {
    width: "30px",
    height: "30px",
    mr: "20px",
    ml: "5px",
  },
  mainProfileBox: {
    // backgroundColor: "#f00",
    p: 3,
    width: "100%",
  },
  dataCard: {
    // backgroundColor: "#0f0",
    p: 2,
    display: "flex",
  },
  profileCard: {
    flex: 1,
    // backgroundColor: "#00f",
    // p: 5,
    m: 1,
    borderRadius: "10px",
    border: "1px solid #e6e6e6",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  detailCard: {
    flex: 2,
    m: 1,
    border: "1px solid #e6e6e6",
    // backgroundColor: "#ff0",
    borderRadius: "10px",
    overflow: "hidden",
    // p: 5,
  },
  divider: {
    width: "100%",
    height: "1px",
    backgroundColor: "#e6e6e6",
    // margin: "10px 0",
    // padding: 2,
  },
  innerProfileCard: {
    padding: 3,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  lowerProfile: {
    padding: 1,
    display: "flex",
    flexDirection: "column",
    // justifyContent: "center",
    // alignItems: "center",
  },
  uploadBtn: {
    // width: "300px",
    color: "#304fa1",
    fontFamily: "Krona One",
    borderRadius: "12px",
    textTransform: "capitalize",
  },
};
