export const DashboardCSS = {
  main: {
    display: "flex",
    minHeight: "80vh",
  },
  sideMain: {
    // position: 'relative',
    // backgroundColor: "#304fa177",
    minWidth: "300px",
    height: "80vh",
    p: 1,
    // overflowY: "scroll",
    // overflowX: "hidden",
  },
  tabTitle: {
    m: 1,
    // py: 0,
    borderRadius: "10px",
    transition: "all 0.3s ease-in-out",
    textTransform: "capitalize",
    textAlign: "left",
    fontFamily: "Krona One",
    fontSize: "1rem",
    display: "flex",
    // height: "20px !important",
    justifyContent: "start",
    alignItems: "center",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#304fa1",
      color: "#fff",
    },
  },
  tabActive: {
    backgroundColor: "#304fa1",
    color: "#fff !important",
  },
  tabIcon: {
    width: "30px",
    height: "30px",
    mr: "20px",
    ml: "5px",
  },
  mainProfileBox: {
    backgroundColor: "#f00",
    p: 4,
    width: "100%",
  },
  dataCard: {
    backgroundColor: "#0f0",
    p: 2,
    display: "flex",
  },
  profileCard: {
    backgroundColor: "#00f",
    p: 5,
    borderRadius: "10px",
    overflow: "hidden",
  },
  detailCard: {
    backgroundColor: "#ff0",
    p: 5,
  },
  divider: {
    width: "100%",
    height: "10vh",
    backgroundColor: "#000",
    margin: "10px 0",
  },
};
